// Copy the Framer fonts/images captured by snapshot.mjs into public/site/ and
// generate app/(site)/fonts.css — Framer's exact @font-face rules (same files,
// unicode ranges and fallback "Placeholder" faces) pointing at the local copies.
//
//   node tools/framer/prepare-assets.mjs
import fs from "node:fs";
import path from "node:path";

const REF = "reference/framer";
const PUBLIC_DIR = "public/site";
const manifest = JSON.parse(fs.readFileSync(path.join(REF, "assets.json"), "utf8"));

// 1. Copy every captured asset to public/site/<same relative path>.
for (const rel of Object.values(manifest)) {
  const src = path.join(REF, "assets", rel);
  const dest = path.join(PUBLIC_DIR, rel);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
}

// 2. Union of @font-face rules across all pages, URLs rewritten to local files.
const faces = new Map();
for (const f of fs.readdirSync(path.join(REF, "raw"))) {
  const html = fs.readFileSync(path.join(REF, "raw", f), "utf8");
  const css = html.match(/<style data-framer-font-css>([\s\S]*?)<\/style>/)?.[1] ?? "";
  for (const m of css.matchAll(/@font-face\s*\{[^}]*\}/g)) {
    const rule = m[0].replace(/url\(\s*["']?([^"')]+)["']?\s*\)/g, (_, url) => {
      const clean = url.split("?")[0];
      const rel = manifest[clean];
      if (!rel) throw new Error(`font not captured: ${clean}`);
      return `url("/site/${rel}")`;
    });
    faces.set(rule, true);
  }
}
const header =
  "/* Generated by tools/framer/prepare-assets.mjs — Framer's exact @font-face rules\n" +
  "   (same font files, unicode ranges and size-adjusted fallbacks), served locally. */\n";
fs.writeFileSync("app/(site)/fonts.css", header + [...faces.keys()].join("\n") + "\n");
console.log(`copied ${Object.keys(manifest).length} assets; ${faces.size} @font-face rules`);
