// Generate app/(site)/text-presets.css — every Framer text style ("preset") used
// on the site, with its per-breakpoint values, as plain CSS classes:
//   .preset-<hash>  (hash = Framer's framer-styles-preset-<hash>)
// Rules are wrapped in :where() so component styles can override any property
// (e.g. colour) regardless of stylesheet order.
//   node tools/framer/text-presets.mjs
import fs from "node:fs";
import path from "node:path";
import { FRAMER_ORIGIN, launch } from "./lib.mjs";

const RAW = "reference/framer/raw";
const PROPS = [
  ["font-family", "font-family"],
  ["font-size", "font-size"],
  ["font-weight", "font-weight"],
  ["font-style", "font-style"],
  ["letter-spacing", "letter-spacing"],
  ["line-height", "line-height"],
  ["text-alignment", "text-align"],
  ["text-color", "color"],
  ["text-transform", "text-transform"],
  ["text-decoration", "text-decoration"],
  ["font-open-type-features", "font-feature-settings"],
  ["font-variation-axes", "font-variation-settings"],
];
const BOLD = [
  ["font-family-bold", "font-family"],
  ["font-weight-bold", "font-weight"],
  ["font-style-bold", "font-style"],
];
const LINK = [
  ["link-text-color", "color"],
  ["link-text-decoration", "text-decoration"],
];

const browser = await launch();
const ctx = await browser.newContext({ javaScriptEnabled: false });
const page = await ctx.newPage();
const presets = new Map(); // hash -> Map(media -> {decl, bold, link, samples})

for (const f of fs.readdirSync(RAW)) {
  const html = fs.readFileSync(path.join(RAW, f), "utf8");
  await page.route(FRAMER_ORIGIN + "/__p", (r) => r.fulfill({ body: html, contentType: "text/html" }));
  await page.goto(FRAMER_ORIGIN + "/__p", { waitUntil: "domcontentloaded" });
  await page.unroute(FRAMER_ORIGIN + "/__p");
  const found = await page.evaluate(
    ({ PROPS, BOLD, LINK }) => {
      const res = [];
      function walk(list, media) {
        for (const r of list) {
          if (r instanceof CSSMediaRule) walk(r.cssRules, r.media.mediaText);
          else if (r instanceof CSSSupportsRule) walk(r.cssRules, media);
          else if (r instanceof CSSStyleRule) {
            const m = r.selectorText.match(/framer-styles-preset-([\w-]+):not\(\.rich-text-wrapper\)/);
            if (!m) continue;
            const pick = (list) =>
              Object.fromEntries(list.map(([v, p]) => [p, r.style.getPropertyValue("--framer-" + v).trim()]).filter(([, x]) => x));
            res.push({ hash: m[1], media: media || "", decl: pick(PROPS), bold: pick(BOLD), link: pick(LINK), spacing: r.style.getPropertyValue("--framer-paragraph-spacing").trim() });
          }
        }
      }
      for (const sh of document.styleSheets) walk(sh.cssRules, null);
      const samples = {};
      for (const el of document.querySelectorAll('[class*="framer-styles-preset-"]')) {
        const h = [...el.classList].find((c) => c.startsWith("framer-styles-preset-"))?.slice(21);
        if (h && !samples[h]) samples[h] = (el.textContent || "").trim().slice(0, 40);
      }
      return { res, samples };
    },
    { PROPS, BOLD, LINK },
  );
  for (const r of found.res) {
    if (!presets.has(r.hash)) presets.set(r.hash, { media: new Map(), sample: "" });
    presets.get(r.hash).media.set(r.media, r);
  }
  for (const [h, t] of Object.entries(found.samples)) if (presets.has(h) && !presets.get(h).sample) presets.get(h).sample = t;
}
await browser.close();

const block = (sel, obj) =>
  Object.keys(obj).length ? `${sel} {\n${Object.entries(obj).map(([k, v]) => `  ${k}: ${v};`).join("\n")}\n}` : "";
let css =
  "/* Generated by tools/framer/text-presets.mjs — Framer text styles, per breakpoint.\n" +
  "   Wrapped in :where() (zero specificity) so component CSS can override anything. */\n";
const order = (m) => (m === "" ? 0 : m.includes("1439") ? 1 : m.includes("1199") ? 2 : 3);
for (const [hash, { media, sample }] of [...presets].sort()) {
  css += `\n/* ${hash}${sample ? ` — e.g. "${sample.replace(/\*\//g, "")}"` : ""} */\n`;
  for (const [m, r] of [...media].sort((a, b) => order(a[0]) - order(b[0]))) {
    const rules = [
      block(`:where(.preset-${hash})`, r.decl),
      block(`:where(.preset-${hash}) :where(strong, b)`, r.bold),
      block(`:where(.preset-${hash}) :where(a)`, r.link),
    ].filter(Boolean);
    if (r.spacing) rules.unshift(`/* paragraph spacing: ${r.spacing} */`);
    css += m ? `@media ${m} {\n${rules.join("\n").replace(/^/gm, "  ")}\n}\n` : rules.join("\n") + "\n";
  }
}
fs.writeFileSync("app/(site)/text-presets.css", css);
console.log(`${presets.size} presets → app/(site)/text-presets.css`);
